
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kalai_portfolio
    username: kalai_profile
    password: Kalai123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

